### ISSUE TITLE
يسطا ايه رأيك تضيف هجوم محدش ضافوا قبل كده 

### ISSUE THREAD

**Issue by minanagehsalalma** [soyalk/probalk#1]
بس هتحتاج تشتغل ع
Evil twin

**Comment by alk99-abderrahman** [comment]
لدي مشروع لا ازال ادرس خوارزميات التشفير ولكن سيكون عبارة عن 
evil twin مشفر 😁

**Comment by minanagehsalalma** [comment]
ايه. ؟!

**Comment by minanagehsalalma** [comment]
لا يوجد  evil twin
مشفر

**Comment by alk99-abderrahman** [comment]
لا ازال اعمل عليه

**Comment by minanagehsalalma** [comment]
ايوا هل يوجد مصادر لما تدرسه او ما شابه ؟

**Comment by minanagehsalalma** [comment]
اذا اردت اضافت فكرتي اخبرني ارسل لك الرابط

**Comment by alk99-abderrahman** [comment]
اوكي اخي
